name: TWRP 14 Minimal Build

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Perform clean build'
        type: boolean
        default: true

env:
  DEVICE: lake
  MANUFACTURER: xiaomi
  TWRP_BRANCH: twrp-14.0
  REPO_URL: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Install repo tool
      run: |
        sudo apt-get update
        sudo apt-get install -y repo
        mkdir -p ~/.bin
        export PATH="$HOME/.bin:$PATH"

    - name: Initialize repo
      run: |
        repo init -u $REPO_URL -b $TWRP_BRANCH --depth=1
        repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle

    - name: Add device tree
      run: |
        mkdir -p device/$MANUFACTURER/$DEVICE
        git clone https://github.com/zobaermd620/redmi14c-lake-twrp-device-tree.git \
          device/$MANUFACTURER/$DEVICE --depth=1

    - name: Prepare build environment
      run: |
        export WITH_TWRP=true
        [ "${{ inputs.clean_build }}" = "true" ] && make clean
        . build/envsetup.sh
        lunch twrp_$DEVICE-eng

    - name: Build recovery
      run: |
        mka -j$(nproc --all) recoveryimage || (echo "Build failed!"; exit 1)

    - name: Upload recovery image
      uses: actions/upload-artifact@v4
      with:
        name: twrp14-$DEVICE-$(date +"%Y%m%d")
        path: out/target/product/$DEVICE/recovery.img
        retention-days: 3
