name: Build TWRP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Droid-Builder Docker image
        run: docker pull fr3akyphantom/droid-builder:latest

      - name: Prepare build directories
        run: |
          mkdir -p $HOME/twrp
          cd $HOME/twrp

          git clone --depth=1 -b twrp-12.1 https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git .
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

          mkdir -p device/xiaomi/lake
          git clone https://github.com/zobaermd620/redmi14c-lake-twrp-device-tree.git device/xiaomi/lake

      - name: Build TWRP in Docker
        run: |
          docker run --rm -i \
            -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) \
            -v "$HOME/twrp:/home/builder/twrp/:rw,z" \
            -v "${HOME}/.ccache:/srv/ccache:rw,z" \
            fr3akyphantom/droid-builder bash << EOF
            cd /home/builder/twrp/
            source build/envsetup.sh
            lunch twrp_lake-eng
            mka recoveryimage
          EOF

      - name: Rename output
        run: |
          cd $HOME/twrp
          version=$(grep "TW_MAIN_VERSION_STR" bootable/recovery/variables.h | cut -d '"' -f2)
          cp out/target/product/lake/recovery.img TWRP-${version}-lake-$(date +"%Y%m%d")-Unofficial.img

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: $HOME/twrp/TWRP-*.img
        env:
          GITHUB_TOKEN: ghp_8ns9oosfve7ntpd6srwmlxrcnnf3hk4pvzmp
