name: TWRP 14 Minimal Build

on:
  workflow_dispatch:
    inputs:
      force_clean:
        description: 'Force clean build'
        type: boolean
        default: false

env:
  DEVICE: lake
  MANUFACTURER: xiaomi
  TWRP_BRANCH: twrp-14.0
  REPO_URL: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    container:
      image: ghcr.io/slim-twrp-builder/android-14:latest
      options: --privileged

    steps:
    - name: Initialize repo
      run: |
        repo init -u $REPO_URL -b $TWRP_BRANCH --depth=1
        repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --optimized-fetch

    - name: Add device tree
      run: |
        mkdir -p device/$MANUFACTURER/$DEVICE
        git clone https://github.com/zobaermd620/redmi14c-lake-twrp-device-tree.git \
          device/$MANUFACTURER/$DEVICE --depth=1 --single-branch

    - name: Prepare build
      run: |
        export WITH_TWRP=true
        export TW_DEVICE_VERSION=$(date +"%Y%m%d")
        [ "${{ inputs.force_clean }}" = "true" ] && make clean
        . build/envsetup.sh
        lunch twrp_$DEVICE-eng

    - name: Build recovery (quiet mode)
      run: |
        mka -j$(nproc --all) recoveryimage > >(tee build.log) 2> >(tee build.err >&2)
        [ $? -eq 0 ] || { echo "Build failed"; exit 1; }

    - name: Generate minimal artifact
      run: |
        mkdir artifact
        cp out/target/product/$DEVICE/recovery.img artifact/
        echo "Build successful" > artifact/status.txt
        tar -cf twrp_${DEVICE}_$(date +"%Y%m%d").tar -C artifact .

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: twrp14_$DEVICE
        path: twrp_*.tar
        retention-days: 3
