name: TWRP Builder - H3000S (Legacy)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (use git@github.com:XXX for SSH)'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-7.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/ycly2333/android_device_EEBBK_H3000S-twrp'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'twrp-7.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/EEBBK/H3000S'
      COMMON_TREE_URL:
        description: 'COMMON_TREE_URL (leave blank if none)'
        required: false
      COMMON_TREE_BRANCH:
        description: 'COMMON_TREE_BRANCH (if common tree exists)'
        required: false
      COMMON_PATH:
        description: 'COMMON_PATH (leave blank if none)'
        required: false
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'H3000S'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'omni_H3000S'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::Build Parameters"
        echo "Manifest: ${{ github.event.inputs.MANIFEST_URL }} (${{ github.event.inputs.MANIFEST_BRANCH }})"
        echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE_URL }} (${{ github.event.inputs.DEVICE_TREE_BRANCH }})"
        echo "Device: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        clean: true  # Replaces third-party cleanup action

    - name: Set Up Environment
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y \
            git-core gnupg flex bison gperf build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z-dev ccache libgl1-mesa-dev \
            libxml2-utils xsltproc unzip python3 python-is-python3

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup SSH Keys (if using SSH URLs)
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') || 
           startsWith(github.event.inputs.DEVICE_TREE_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo
      run: |
        mkdir -p workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: repo_init

    - name: Repo Sync
      run: repo sync -j$(nproc --all) --force-sync
      working-directory: ${{ steps.repo_init.outputs.workspace-folder }}

    - name: Clone Device Tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} \
          -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
          ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.repo_init.outputs.workspace-folder }}

    - name: Clone Common Tree (if specified)
      if: ${{ inputs.COMMON_TREE_URL != '' && inputs.COMMON_PATH != '' }}
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} \
          -b ${{ github.event.inputs.COMMON_TREE_BRANCH || github.event.inputs.DEVICE_TREE_BRANCH }} \
          ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.repo_init.outputs.workspace-folder }}

    - name: Build Recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make -j$(nproc --all) ${{ github.event.inputs.BUILD_TARGET }}image
      working-directory: ${{ steps.repo_init.outputs.workspace-folder }}

    - name: Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.repo_init.outputs.workspace-folder }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
          ${{ steps.repo_init.outputs.workspace-folder }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
        tag_name: twrp-${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_number }}
        body: |
          TWRP build for ${{ github.event.inputs.DEVICE_NAME }}
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device Tree: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
